import * as THREE from 'three';

const mat=(color,metalness=.45,roughness=.35,opts={})=>new THREE.MeshPhysicalMaterial({color,metalness,roughness,...opts});

export class Car{
  constructor(scene,{police=false,color=0x9b0f18,armored=false,spec=null}={}){
    this.scene=scene;this.group=new THREE.Group();this.scene.add(this.group);
    this.velocity=0;this.heading=0;this.steer=0;this.damage=0;this.police=police;this.armored=armored;this.spec=spec;
    this.tankLiters=spec?.tankLiters||(spec?.style==='ev'?88:68);this.fuel=spec?.initialFuel??this.tankLiters;this.consumption=spec?.consumption||(spec?.style==='ev'?10.5:14.5);
    const p=spec?.physics||{};this.maxSpeed=armored?49:(police?66:(p.maxSpeed||84));this.accel=armored?20:(police?27:(p.accel||35));this.brakeForce=p.brake||45;this.dragGas=p.dragGas??.085;this.dragCoast=p.dragCoast??.30;this.steerRate=p.steerRate||.0205;this.grip=p.grip||1;
    this.wheels=[];this.strobes=[];this.lightMeshes=[];this.tailMeshes=[];this.headMeshes=[];this.bodyMaterials=[];this.glassMaterials=[];this.damageParts=[];this.crackOverlay=null;this.doorPivot=null;this.doorOpen=0;this.doorTarget=0;this.steeringWheel=null;this.dashGlow=null;this.wipers=[];this.rainScreen=null;this.rainLevel=0;this.wiperPhase=0;this.style=spec?.style||'super';
    this._make(spec?.color??color,this.style,spec?.accent||0xff7d15);this.reset(police?[-40,0,-35]:[0,0,0]);
  }
  _mesh(geo,material,pos=[0,0,0],rot=[0,0,0],parent=this.group){const m=new THREE.Mesh(geo,material);m.position.set(...pos);m.rotation.set(...rot);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
  _make(color,style,accent){
    const body=mat(color,.92,.11,{clearcoat:1,clearcoatRoughness:.045}),body2=mat(new THREE.Color(color).offsetHSL(0,0,-.07),.9,.14,{clearcoat:1,clearcoatRoughness:.06});this.bodyMaterials.push(body,body2);
    const carbon=mat(0x07090d,.86,.20,{clearcoat:.35,clearcoatRoughness:.18}),dark=mat(0x080a0f,.58,.23),glass=mat(0x07131d,.72,.055,{transmission:.18,transparent:true,opacity:.74,clearcoat:.8}),chrome=mat(0x828991,.96,.09),tire=mat(0x08090b,.04,.86),rim=mat(0x2d3138,.92,.16),disc=mat(0x7f858c,.82,.26),brake=mat(this.police?0x315dff:accent,.58,.28);this.glassMaterials.push(glass);
    if(style==='scooter'){
      const frame=this._mesh(new THREE.BoxGeometry(.42,.34,1.45),body,[0,.64,.08]);frame.rotation.x=-.06;this._mesh(new THREE.BoxGeometry(.38,.18,.62),body2,[0,.92,.12],[-.2,0,0]);this._mesh(new THREE.BoxGeometry(.44,.12,.48),dark,[0,.87,.40]);this._mesh(new THREE.CylinderGeometry(.05,.05,.85,8),chrome,[0,1.18,-.48],[-.18,0,0]);this._mesh(new THREE.BoxGeometry(.72,.05,.05),chrome,[0,1.48,-.62]);
      for(const z of [-.67,.72]){const wg=new THREE.Group();wg.position.set(0,.42,z);this.group.add(wg);const t=this._mesh(new THREE.TorusGeometry(.29,.07,8,16),tire,[0,0,0],[0,Math.PI/2,0],wg);const hub=this._mesh(new THREE.CylinderGeometry(.07,.07,.10,12),rim,[0,0,0],[0,0,Math.PI/2],wg);this.wheels.push(wg);}this._mesh(new THREE.BoxGeometry(.20,.06,.035),new THREE.MeshBasicMaterial({color:0xff2921,toneMapped:false}),[0,.72,.83]);
    }else if(style==='bus'){
      this._mesh(new THREE.BoxGeometry(2.36,1.08,7.7),body,[0,1.02,0]);this._mesh(new THREE.BoxGeometry(2.18,1.10,6.95),glass,[0,1.82,-.10]);this._mesh(new THREE.BoxGeometry(2.24,.18,7.45),body2,[0,2.36,0]);this._mesh(new THREE.BoxGeometry(1.35,.22,.08),new THREE.MeshBasicMaterial({color:0x5fe7ff,toneMapped:false}),[0,1.78,-3.88]);
    }else if(style==='utility'){
      this._mesh(new THREE.BoxGeometry(2.08,.42,4.75),body,[0,.66,.10]);this._mesh(new THREE.BoxGeometry(1.86,.62,1.80),glass,[0,1.12,-.78]);this._mesh(new THREE.BoxGeometry(1.92,.28,1.62),body2,[0,.78,1.38]);this._mesh(new THREE.BoxGeometry(1.72,.10,1.42),carbon,[0,.93,1.38]);
    }else if(this.armored){
      this._mesh(new THREE.BoxGeometry(2.45,.82,5.1),mat(0x111820,.75,.42),[0,.86,0]);this._mesh(new THREE.BoxGeometry(2.18,.78,2.35),mat(0x151d25,.7,.38),[0,1.56,.35]);this._mesh(new THREE.BoxGeometry(2.3,.2,.72),carbon,[0,.47,-2.32]);this._mesh(new THREE.BoxGeometry(2.35,.26,.68),carbon,[0,.58,2.35]);
    }else if(style==='retro'){
      this._mesh(new THREE.BoxGeometry(2.12,.38,4.65),body,[0,.64,.05]);this._mesh(new THREE.BoxGeometry(1.86,.28,1.25),body2,[0,.91,-1.45],[-.06,0,0]);this._mesh(new THREE.BoxGeometry(1.72,.62,1.78),glass,[0,1.21,.10]);this._mesh(new THREE.BoxGeometry(1.88,.12,.65),carbon,[0,.48,2.24]);this._mesh(new THREE.BoxGeometry(1.76,.09,.22),carbon,[0,1.22,2.04]);
    }else{
      const length=style==='gt'?4.95:style==='hyper'?4.82:style==='ev'?4.9:4.7;this._mesh(new THREE.BoxGeometry(2.18,.36,length),body,[0,.61,.05]);this._mesh(new THREE.BoxGeometry(style==='hyper'?1.95:2.02,.24,1.7),body2,[0,.88,-1.48],[-.10,0,0]);this._mesh(new THREE.BoxGeometry(style==='gt'?1.72:1.64,style==='gt'?.68:.56,style==='gt'?1.95:1.76),glass,[0,1.18,.08],[-.045,0,0]);this._mesh(new THREE.BoxGeometry(1.72,.075,1.0),carbon,[0,1.03,-.03],[-.16,0,0]);
      this.damageParts.push(this._mesh(new THREE.BoxGeometry(2.0,.08,.62),carbon,[0,.40,-2.18]));this._mesh(new THREE.BoxGeometry(2.0,.10,.52),carbon,[0,.43,2.20]);
      if(['track','hyper'].includes(style)){const wingW=style==='hyper'?1.72:1.88;this._mesh(new THREE.BoxGeometry(wingW,.075,.32),carbon,[0,1.24,2.10]);this._mesh(new THREE.BoxGeometry(.10,.40,.10),carbon,[-.67,1.02,2.04]);this._mesh(new THREE.BoxGeometry(.10,.40,.10),carbon,[.67,1.02,2.04]);}
      if(style==='hyper')for(const x of [-.86,.86])this._mesh(new THREE.BoxGeometry(.12,.25,1.25),carbon,[x,.55,1.35],[0,0,x<0?-.11:.11]);if(style==='ev')this._mesh(new THREE.BoxGeometry(1.58,.04,.08),new THREE.MeshBasicMaterial({color:0x76efff,toneMapped:false}),[0,.89,-2.43]);
    }
    if(!this.armored&&style!=='scooter'&&style!=='bus'){
      this._mesh(new THREE.BoxGeometry(.11,.18,2.55),carbon,[-1.08,.48,.28]);this._mesh(new THREE.BoxGeometry(.11,.18,2.55),carbon,[1.08,.48,.28]);for(const x of [-1.12,1.12])this._mesh(new THREE.BoxGeometry(.20,.09,.30),body,[x,1.04,-.42]);if(style!=='ev')for(const x of [-.36,.36])this._mesh(new THREE.CylinderGeometry(.075,.075,.18,16),chrome,[x,.51,2.39],[Math.PI/2,0,0]);this._mesh(new THREE.BoxGeometry(.72,.18,.025),mat(0xe8e9e9,.1,.55),[0,.61,2.46]);this._cockpit(dark,carbon,accent,style);this._door(body,glass);this._windshieldFX(style,dark);
    }
    if(style!=='scooter'){
      const wz=style==='bus'?2.72:(style==='gt'?1.56:1.48),wx=style==='bus'?1.12:1.03;for(const x of [-wx,wx])for(const z of [-wz,wz]){const wg=new THREE.Group();wg.position.set(x,.48,z);this.group.add(wg);const t=new THREE.Mesh(new THREE.CylinderGeometry(.405,.405,.31,32),tire);t.rotation.z=Math.PI/2;t.castShadow=true;wg.add(t);const d=new THREE.Mesh(new THREE.CylinderGeometry(.245,.245,.035,28),disc);d.rotation.z=Math.PI/2;wg.add(d);const r=new THREE.Mesh(new THREE.CylinderGeometry(.29,.29,.325,12),rim);r.rotation.z=Math.PI/2;wg.add(r);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.34,12),chrome);hub.rotation.z=Math.PI/2;wg.add(hub);const cal=new THREE.Mesh(new THREE.BoxGeometry(.07,.26,.11),brake);cal.position.set(x<0?.05:-.05,.05,0);wg.add(cal);this.wheels.push(wg);}
    }
    const tail=new THREE.MeshBasicMaterial({color:0xff2019,toneMapped:false}),head=new THREE.MeshBasicMaterial({color:0xe7f7ff,toneMapped:false}),endZ=style==='bus'?3.86:2.39,frontZ=style==='bus'?-3.87:-2.40;if(style!=='scooter')for(const x of [-.68,.68]){const tm=this._mesh(new THREE.BoxGeometry(.58,.075,.055),tail.clone(),[x,.82,endZ]);tm.castShadow=false;this.tailMeshes.push(tm);const hm=this._mesh(new THREE.BoxGeometry(.55,.07,.055),head.clone(),[x,.80,frontZ]);hm.castShadow=false;this.headMeshes.push(hm);}if(style!=='scooter'&&style!=='bus')for(const x of [-.74,.74]){const hm=this._mesh(new THREE.BoxGeometry(.42,.03,.03),head.clone(),[x,.91,-2.43],[0,0,x<0?.08:-.08]);hm.castShadow=false;this.headMeshes.push(hm);}
    if(!this.police&&!this.armored&&style!=='scooter'){for(const x of [-.62,.62]){const light=new THREE.SpotLight(0xe9f7ff,72,72,.30,.52,1.7);light.position.set(x,.90,style==='bus'?-3.45:-2.05);const target=new THREE.Object3D();target.position.set(x*.45,.30,-32);this.group.add(target);light.target=target;this.group.add(light);this.lightMeshes.push(light);}const rearGlow=new THREE.PointLight(0xff241c,4.5,7,2);rearGlow.position.set(0,.76,style==='bus'?3.52:2.16);this.group.add(rearGlow);this.lightMeshes.push(rearGlow);}
    if(this.police){const base=this._mesh(new THREE.BoxGeometry(1.28,.08,.28),dark,[0,this.armored?2.05:1.63,.10]),red=new THREE.MeshBasicMaterial({color:0xff2441,toneMapped:false}),blue=new THREE.MeshBasicMaterial({color:0x2677ff,toneMapped:false});const l=new THREE.Mesh(new THREE.BoxGeometry(.58,.09,.24),red);l.position.x=-.31;base.add(l);const r=new THREE.Mesh(new THREE.BoxGeometry(.58,.09,.24),blue);r.position.x=.31;base.add(r);this.strobes.push(l,r);for(const [x,c] of [[-.45,red],[.45,blue]]){const s=new THREE.Mesh(new THREE.BoxGeometry(.18,.08,.025),c);s.position.set(x,.72,-2.45);this.group.add(s);this.strobes.push(s);}}
    if(style!=='scooter')this._crackedGlass(style);
    this.cockpitAnchor=new THREE.Object3D();this.cockpitAnchor.position.set(style==='scooter'?0:-.34,style==='scooter'?1.45:1.34,style==='scooter'?-.18:-.34);this.group.add(this.cockpitAnchor);this.cockpitLook=new THREE.Object3D();this.cockpitLook.position.set(0,style==='scooter'?1.45:1.30,style==='scooter'?-12:-18);this.group.add(this.cockpitLook);
  }
  _crackedGlass(style){
    const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='rgba(225,242,255,.88)';x.lineWidth=1.15;const cx=310,cy=122;for(let r=0;r<18;r++){const a=(r/18)*Math.PI*2+(r%3)*.08,rr=34+(r%5)*14;x.beginPath();x.moveTo(cx,cy);let px=cx,py=cy;for(let k=1;k<=5;k++){const rad=rr*k/5,ang=a+Math.sin(r*1.7+k)*.08,xx=cx+Math.cos(ang)*rad,yy=cy+Math.sin(ang)*rad*.72;x.lineTo(xx,yy);px=xx;py=yy;}x.stroke();if(r%3===0){x.beginPath();x.arc(px,py,7+(r%4)*3,0,Math.PI*1.4);x.stroke();}}for(let i=0;i<7;i++){x.beginPath();x.arc(cx,cy,10+i*8,(i*.7)%6.28,((i*.7)+2.8)%6.28);x.stroke();}
    const tex=new THREE.CanvasTexture(c);const m=new THREE.MeshBasicMaterial({map:tex,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide,toneMapped:false});const w=style==='bus'?2.0:1.55,h=style==='bus'?.72:.62,z=style==='bus'?-3.88:-.91,y=style==='bus'?1.83:1.31;this.crackOverlay=this._mesh(new THREE.PlaneGeometry(w,h),m,[0,y,z],[-.12,0,0]);this.crackOverlay.visible=false;this.crackOverlay.castShadow=false;
  }
  _cockpit(dark,carbon,accent,style){
    const leather=mat(0x111216,.08,.62),stitch=mat(0x2a2c31,.05,.74),glow=new THREE.MeshBasicMaterial({color:accent,toneMapped:false});this._mesh(new THREE.BoxGeometry(1.70,.16,.55),dark,[0,1.08,-.52],[-.17,0,0]);this._mesh(new THREE.BoxGeometry(.94,.06,.36),carbon,[0,1.18,-.63],[-.18,0,0]);
    for(const x of [-.46,.46]){const seat=this._mesh(new THREE.BoxGeometry(.52,.62,.58),leather,[x,.80,.35],[-.08,0,0]);const head=this._mesh(new THREE.BoxGeometry(.42,.34,.22),leather,[x,1.20,.50],[-.08,0,0]);}
    this.steeringWheel=this._mesh(new THREE.TorusGeometry(.18,.026,8,20),stitch,[-.36,1.20,-.48],[Math.PI/2,0,0]);this._mesh(new THREE.CylinderGeometry(.045,.045,.20,10),dark,[-.36,1.19,-.44],[Math.PI/2,0,0]);this.dashGlow=this._mesh(new THREE.BoxGeometry(.54,.17,.025),glow,[-.02,1.26,-.72],[-.12,0,0]);this._mesh(new THREE.BoxGeometry(.18,.055,.025),new THREE.MeshBasicMaterial({color:0xe7f5ff,toneMapped:false}),[-.36,1.27,-.71],[-.12,0,0]);
  }
  _door(body,glass){this.doorPivot=new THREE.Group();this.doorPivot.position.set(-1.05,.92,-.55);this.group.add(this.doorPivot);const panel=this._mesh(new THREE.BoxGeometry(.09,.54,1.72),body,[0,0,.78],[0,0,0],this.doorPivot);const window=this._mesh(new THREE.BoxGeometry(.035,.34,.82),glass,[-.01,.35,.46],[0,0,0],this.doorPivot);panel.castShadow=true;window.castShadow=false;}
  _windshieldFX(style,dark){
    const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');x.clearRect(0,0,512,256);
    for(let i=0;i<190;i++){const px=(i*83)%512,py=(i*47)%256,r=.7+((i*13)%9)*.22;x.beginPath();x.ellipse(px,py,r*.55,r*2.2,.12,0,Math.PI*2);x.fillStyle=`rgba(205,235,255,${.10+((i%7)/100)})`;x.fill();}
    const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const rm=new THREE.MeshBasicMaterial({map:tex,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide,toneMapped:false});
    this.rainScreen=this._mesh(new THREE.PlaneGeometry(1.58,.64),rm,[0,1.315,-.935],[-.12,0,0]);this.rainScreen.castShadow=false;this.rainScreen.renderOrder=9;
    for(const sx of [-.34,.34]){const pivot=new THREE.Group();pivot.position.set(sx,1.08,-.955);this.group.add(pivot);const arm=this._mesh(new THREE.BoxGeometry(.035,.52,.025),dark,[0,.24,0],[0,0,sx<0?.18:-.18],pivot);arm.castShadow=false;const blade=this._mesh(new THREE.BoxGeometry(.035,.42,.018),new THREE.MeshStandardMaterial({color:0x101316,roughness:.9}),[0,.48,0],[0,0,sx<0?-.10:.10],pivot);blade.castShadow=false;this.wipers.push(pivot);}
  }
  setWeather(rain=0,inTunnel=false){this.rainLevel=inTunnel?0:THREE.MathUtils.clamp(rain,0,1);if(this.rainScreen)this.rainScreen.material.opacity=this.rainLevel*.34;}
  setDoorOpen(open=true){this.doorTarget=open?1:0;}
  cockpitWorld(out=new THREE.Vector3()){return this.cockpitAnchor?.getWorldPosition(out)||this.group.getWorldPosition(out);}
  cockpitLookWorld(out=new THREE.Vector3()){return this.cockpitLook?.getWorldPosition(out)||this.group.getWorldPosition(out);}
  reset(p=[0,0,0]){this.group.position.set(...p);this.group.position.y=.04;this.velocity=0;this.heading=0;this.group.rotation.set(0,0,0);this.damage=0;this.doorOpen=this.doorTarget=0;if(this.doorPivot)this.doorPivot.rotation.y=0;}
  refuel(){this.fuel=this.tankLiters;}get fuelPct(){return this.tankLiters?THREE.MathUtils.clamp(this.fuel/this.tankLiters,0,1):0;}
  update(dt,input,colliders=[]){
    this._animateDetails(dt);let gas=input.gas?1:0;const brake=input.brake?1:0,hb=input.handbrake?1:0;if(this.fuel<=0)gas=0;let force=gas*this.accel-brake*this.brakeForce;force-=this.velocity*(gas?this.dragGas:this.dragCoast);this.velocity+=force*dt;this.velocity=THREE.MathUtils.clamp(this.velocity,-11,this.maxSpeed*(1-this.damage*.0028));
    const steerTarget=(input.left?1:0)-(input.right?1:0);this.steer=THREE.MathUtils.lerp(this.steer,steerTarget,Math.min(1,dt*(hb?11:8)));const speedFactor=Math.min(1,Math.abs(this.velocity)/9),highSpeedAssist=THREE.MathUtils.lerp(1,.67,Math.min(1,Math.abs(this.velocity)/this.maxSpeed));this.heading+=this.steer*this.velocity*dt*this.steerRate*(hb?1.72:1)*(.20+.80*speedFactor)*highSpeedAssist*this.grip;this.group.rotation.y=this.heading;
    this.group.rotation.z=THREE.MathUtils.lerp(this.group.rotation.z,-this.steer*Math.min(.06,Math.abs(this.velocity)*.00125),dt*5);this.group.rotation.x=THREE.MathUtils.lerp(this.group.rotation.x,gas?-.012:(brake?.02:0),dt*4);const dir=new THREE.Vector3(-Math.sin(this.heading),0,-Math.cos(this.heading)),before=this.group.position.clone();this.group.position.addScaledVector(dir,this.velocity*dt);if(this.group.position.length()>24500){this.group.position.copy(before);this.velocity*=-.3;}
    const p=this.group.position;for(const b of colliders){if(p.x>b.min.x-1.15&&p.x<b.max.x+1.15&&p.z>b.min.z-2.15&&p.z<b.max.z+2.15){this.group.position.copy(before);const hit=Math.abs(this.velocity);this.velocity*=-.22;this.damage=Math.min(100,this.damage+1.8+hit*.11);break;}}
    const meters=Math.abs(this.velocity)*dt;if(!this.police&&!this.armored&&this.tankLiters)this.fuel=Math.max(0,this.fuel-(meters/100000)*this.consumption*3.2-gas*dt*.0008);this._damageVisual(brake);for(const w of this.wheels)w.rotation.x-=this.velocity*dt*.62;this._strobe(performance.now()*.001);
  }
  chase(dt,target,aggression=1){
    this._animateDetails(dt);const to=target.clone().sub(this.group.position),d=to.length(),desired=Math.atan2(-to.x,-to.z),diff=Math.atan2(Math.sin(desired-this.heading),Math.cos(desired-this.heading));this.heading+=THREE.MathUtils.clamp(diff,-1.05,1.05)*dt*(1.0+aggression*.35+Math.min(1,this.velocity/30));this.velocity=THREE.MathUtils.lerp(this.velocity,Math.min(this.maxSpeed,20+d*.075+aggression*3),dt*(.55+aggression*.14));const dir=new THREE.Vector3(-Math.sin(this.heading),0,-Math.cos(this.heading));this.group.position.addScaledVector(dir,this.velocity*dt);this.group.rotation.y=this.heading;for(const w of this.wheels)w.rotation.x-=this.velocity*dt*.62;this._strobe(performance.now()*.001);
  }
  _animateDetails(dt){if(this.doorPivot){this.doorOpen=THREE.MathUtils.damp(this.doorOpen,this.doorTarget,9,dt);this.doorPivot.rotation.y=-this.doorOpen*1.05;}if(this.steeringWheel)this.steeringWheel.rotation.z=-this.steer*.72;if(this.dashGlow){const pulse=.86+Math.sin(performance.now()*.004)*.08;this.dashGlow.material.opacity=pulse;this.dashGlow.material.transparent=true;}if(this.wipers.length){const rate=this.rainLevel>.75?4.6:this.rainLevel>.25?2.8:this.rainLevel>.04?1.6:0;if(rate>0)this.wiperPhase=(this.wiperPhase+dt*rate)%2;const wp=this.wiperPhase<1?this.wiperPhase:2-this.wiperPhase;const sweep=rate?Math.sin(wp*Math.PI):0;for(const [i,w] of this.wipers.entries())w.rotation.z=THREE.MathUtils.lerp(w.rotation.z,(i?-.72:.72)*sweep,Math.min(1,dt*12));if(this.rainScreen){const clear=.45+.55*(1-Math.abs(Math.sin(this.wiperPhase*Math.PI)));this.rainScreen.material.opacity=this.rainLevel*.34*clear;}}}
  _damageVisual(braking=false){const dmg=this.damage/100;for(const m of this.bodyMaterials){m.roughness=THREE.MathUtils.lerp(.11,.48,dmg);m.clearcoat=THREE.MathUtils.lerp(1,.35,dmg);}for(const g of this.glassMaterials){g.roughness=THREE.MathUtils.lerp(.055,.22,Math.max(0,dmg-.38)*1.6);g.opacity=THREE.MathUtils.lerp(.74,.58,Math.max(0,dmg-.5)*2);}if(this.crackOverlay){this.crackOverlay.visible=dmg>.48;this.crackOverlay.material.opacity=THREE.MathUtils.clamp((dmg-.48)*1.85,0,.92);}for(const t of this.tailMeshes){t.scale.y=braking?1.45:1;t.material.color.setHex(braking?0xff4b35:0xff2019);}for(const [i,p] of this.damageParts.entries()){p.rotation.x=dmg>.45?.05*dmg:0;p.position.y=.40-Math.max(0,dmg-.55)*.13;}for(const [i,h] of this.headMeshes.entries())if(dmg>.72&&i===0)h.visible=Math.floor(performance.now()/180)%3!==0;}
  idle(dt){this._animateDetails(dt);this._damageVisual(false);this._strobe(performance.now()*.001);}
  _strobe(t){if(!this.strobes.length)return;const phase=Math.floor(t*9)%4;this.strobes.forEach((s,i)=>s.visible=((phase<2)?i%2===0:i%2===1));}
  get speedKmh(){return Math.abs(this.velocity)*3.6;}
}
