export class HUD{
  constructor(){
    this.speed=document.querySelector('#speed');this.gear=document.querySelector('#gear');this.stars=document.querySelector('#stars');this.body=document.querySelector('#body');this.engine=document.querySelector('#engine');this.search=document.querySelector('#search');this.rep=document.querySelector('#rep');this.fuel=document.querySelector('#fuel');this.mode=document.querySelector('#mode');this.stamina=document.querySelector('#stamina');this.clock=document.querySelector('#clock');this.weather=document.querySelector('#weather');this.district=document.querySelector('#district');this.message=document.querySelector('#message');this.alert=document.querySelector('#alert');this.heat=document.querySelector('#heatText');this.map=document.querySelector('#minimap');this.ctx=this.map?.getContext('2d');
  }
  update(entity,pursuit,roads,progress,state={}){
    const s=Math.round(entity?.speedKmh||0);this.speed.textContent=String(s).padStart(3,'0');this.gear.textContent=state.onFoot?'WALK':(s<2?'N':Math.min(7,1+Math.floor(s/41)));
    const stars=Math.ceil(pursuit.heat);this.stars.textContent='★'.repeat(stars)+'☆'.repeat(6-stars);this.body.textContent=`${Math.max(0,Math.round(100-(entity?.damage||0)))}%`;this.engine.textContent=state.onFoot?'—':`${Math.max(0,Math.round(state.fuelPct>0?100-(entity?.damage||0)*.62:0))}%`;this.search.textContent=pursuit.search>.58?'鎖定':pursuit.search>.13?'搜索中':'脫離';if(this.rep)this.rep.textContent=Math.floor(progress?.rep||0).toLocaleString();if(this.fuel)this.fuel.textContent=state.onFoot?'—':`${Math.round((state.fuelPct||0)*100)}%`;if(this.mode)this.mode.textContent=state.onFoot?'徒步':(state.vehicleName||'駕駛中');if(this.stamina)this.stamina.textContent=state.onFoot?`${Math.round((state.staminaPct||0)*100)}%`:'—';this.heat.textContent=`${stars} / 6`;this.alert.textContent=pursuit.alert;
    if(state.district)this.district.textContent=state.district;if(this.clock&&state.time)this.clock.textContent=state.time;if(this.weather&&state.weather)this.weather.textContent=state.weather;
    this.message.textContent=state.prompt||(!state.onFoot&&state.fuelPct<=.08?'燃料即將耗盡 · 尋找加油站':pursuit.search>.58?'甩開追緝單位 · 利用街區切斷視線':'保持隱蔽 · 搜索強度正在下降');
    this._map(entity,pursuit,roads,state.onFoot);
  }
  _map(entity,pursuit,roads,onFoot){if(!this.ctx||!entity)return;const c=this.ctx,W=this.map.width,H=this.map.height;c.clearRect(0,0,W,H);const grad=c.createRadialGradient(W/2,H/2,8,W/2,H/2,W/2);grad.addColorStop(0,'#111922');grad.addColorStop(1,'#05080c');c.fillStyle=grad;c.fillRect(0,0,W,H);c.save();c.translate(W/2,H/2);c.rotate(-entity.heading);const sc=.058;c.strokeStyle='rgba(214,226,236,.19)';c.lineWidth=4;for(const r of roads){if(!r?.points?.length)continue;c.beginPath();let drawn=0;for(let i=0;i<r.points.length;i++){const p=r.points[i],dx=(p.x-entity.group.position.x)*sc,dz=(p.y-entity.group.position.z)*sc;if(Math.abs(dx)>W||Math.abs(dz)>H)continue;drawn++;drawn===1?c.moveTo(dx,dz):c.lineTo(dx,dz);}if(drawn>1)c.stroke();}c.restore();c.fillStyle=onFoot?'#78e6ff':'#f4f7fb';c.beginPath();c.moveTo(W/2,H/2-7);c.lineTo(W/2-5,H/2+6);c.lineTo(W/2+5,H/2+6);c.closePath();c.fill();c.fillStyle='#4d8dff';for(const u of pursuit.units){const dx=(u.group.position.x-entity.group.position.x)*sc,dz=(u.group.position.z-entity.group.position.z)*sc;if(Math.abs(dx)<W/2&&Math.abs(dz)<H/2){c.beginPath();c.arc(W/2+dx,H/2+dz,3.2,0,Math.PI*2);c.fill();}}c.strokeStyle='rgba(255,72,72,.35)';c.lineWidth=2;c.beginPath();c.arc(W/2,H/2,52,0,Math.PI*2);c.stroke();}
}
