import * as THREE from 'three';

const bodyMat=(color)=>new THREE.MeshPhysicalMaterial({color,metalness:.62,roughness:.24,clearcoat:.72,clearcoatRoughness:.08});
const dark=new THREE.MeshStandardMaterial({color:0x090b0e,roughness:.35});
const glass=new THREE.MeshPhysicalMaterial({color:0x10202a,metalness:.55,roughness:.12,transmission:.08,transparent:true,opacity:.82,clearcoat:.6});
const headMat=new THREE.MeshBasicMaterial({color:0xe4f4ff,toneMapped:false});

function wheel(g,x,z,r=.31){const w=new THREE.Mesh(new THREE.CylinderGeometry(r,r,.22,14),dark);w.rotation.z=Math.PI/2;w.position.set(x,r+.03,z);g.add(w);}
function tail(g,x,y,z,arr){const t=new THREE.Mesh(new THREE.BoxGeometry(.34,.07,.03),new THREE.MeshBasicMaterial({color:0xff3025,toneMapped:false,transparent:true,opacity:.7}));t.position.set(x,y,z);g.add(t);arr.push(t);}
function makeTrafficVehicle(color,type='sedan'){
  const g=new THREE.Group(),body=bodyMat(color),brake=[];
  let L=3.9,W=1.72,H=.55;
  if(type==='van'){L=4.6;W=1.9;H=.78;}else if(type==='compact'){L=3.5;W=1.66;H=.52;}else if(type==='pickup'){L=4.65;W=1.88;H=.62;}else if(type==='bus'){L=7.8;W=2.35;H=1.2;}else if(type==='scooter'){L=1.75;W=.72;H=.35;}
  if(type==='scooter'){
    const frame=new THREE.Mesh(new THREE.BoxGeometry(.38,.34,1.30),body);frame.position.y=.62;frame.rotation.x=-.05;g.add(frame);const cowl=new THREE.Mesh(new THREE.BoxGeometry(.42,.42,.44),body);cowl.position.set(0,.82,-.42);g.add(cowl);const seat=new THREE.Mesh(new THREE.BoxGeometry(.34,.12,.52),dark);seat.position.set(0,.90,.24);g.add(seat);for(const z of [-.62,.66]){const w=new THREE.Mesh(new THREE.TorusGeometry(.27,.065,8,14),dark);w.rotation.y=Math.PI/2;w.position.set(0,.34,z);g.add(w);}const riderBody=new THREE.Mesh(new THREE.CapsuleGeometry(.16,.48,3,7),new THREE.MeshStandardMaterial({color:0x253342,roughness:.8}));riderBody.position.set(0,1.38,.08);g.add(riderBody);const riderHead=new THREE.Mesh(new THREE.SphereGeometry(.15,8,7),new THREE.MeshStandardMaterial({color:0xd0a082,roughness:.78}));riderHead.position.set(0,1.75,-.06);g.add(riderHead);const helmet=new THREE.Mesh(new THREE.SphereGeometry(.18,9,7,0,Math.PI*2,0,Math.PI/1.7),new THREE.MeshStandardMaterial({color:0x1c2028,roughness:.4,metalness:.2}));helmet.position.set(0,1.79,-.06);g.add(helmet);tail(g,0,.68,.88,brake);
  }else if(type==='bus'){
    const base=new THREE.Mesh(new THREE.BoxGeometry(W,H,L),body);base.position.y=.88;base.castShadow=true;g.add(base);const cab=new THREE.Mesh(new THREE.BoxGeometry(W-.15,1.15,L-.3),glass);cab.position.set(0,1.72,.02);g.add(cab);for(const x of [-.8,.8])for(const z of [-2.65,2.6])wheel(g,x,z,.38);for(let i=0;i<5;i++){const wnd=new THREE.Mesh(new THREE.BoxGeometry(W+.02,.48,.72),glass);wnd.position.set(0,1.7,-2+i*1.05);g.add(wnd);}tail(g,-.72,.9,L/2+.02,brake);tail(g,.72,.9,L/2+.02,brake);
  }else{
    const base=new THREE.Mesh(new THREE.BoxGeometry(W,H,L),body);base.position.y=.56;base.castShadow=true;g.add(base);
    if(type==='pickup'){const cab=new THREE.Mesh(new THREE.BoxGeometry(W-.18,.65,1.85),glass);cab.position.set(0,1.08,-.67);g.add(cab);const bed=new THREE.Mesh(new THREE.BoxGeometry(W-.16,.28,1.55),new THREE.MeshStandardMaterial({color:new THREE.Color(color).offsetHSL(0,0,-.08),roughness:.4,metalness:.4}));bed.position.set(0,.72,1.28);g.add(bed);}else{const cab=new THREE.Mesh(new THREE.BoxGeometry(W-.24,type==='van'?.72:.54,type==='van'?2.45:1.72),glass);cab.position.set(0,type==='van'?1.2:1.02,type==='van'?.15:.1);cab.castShadow=true;g.add(cab);}for(const x of [-(W/2-.08),(W/2-.08)])for(const z of [-L*.30,L*.31])wheel(g,x,z,type==='van'?.34:.31);for(const x of [-.52,.52]){const h=new THREE.Mesh(new THREE.BoxGeometry(.34,.07,.03),headMat);h.position.set(x,.62,-L/2-.02);g.add(h);tail(g,x,.64,L/2+.02,brake);}const plate=new THREE.Mesh(new THREE.BoxGeometry(.62,.15,.025),new THREE.MeshStandardMaterial({color:0xdde4e6,roughness:.55}));plate.position.set(0,.53,L/2+.035);g.add(plate);
  }
  g.userData={length:L,width:W,brake,type};return g;
}

export class Traffic{
  constructor(scene,roads,count=20){this.scene=scene;this.roads=roads.filter(r=>r.points?.length>1&&r.width>=6);this.cars=[];this.targetCount=count;this.seq=0;this.events=[];this.spawn(count);}
  spawn(n){
    if(!this.roads.length)return;const colors=[0x303945,0x9b9b95,0x1f405f,0x632e2d,0xd2d2cf,0x172321,0x6c593c,0x7e2830,0x1c5b68,0xe2e0d9];const types=['sedan','compact','sedan','van','scooter','pickup','sedan','scooter','compact','bus'];
    for(let i=0;i<n;i++){const r=this.roads[(i*7+this.seq)%this.roads.length];if(!r)continue;let type=types[(i+this.seq)%types.length];if(type==='bus'&&r.width<9)type='van';const color=colors[(i*3+this.seq)%colors.length],mesh=makeTrafficVehicle(color,type),seg=(i*11+this.seq)%Math.max(1,r.points.length-1),a=r.points[seg],b=r.points[seg+1];if(!a||!b)continue;const heading=Math.atan2(b.x-a.x,b.y-a.y),lane=(i%2?1:-1)*Math.min(type==='scooter'?.95:1.65,r.width*.18),nx=Math.cos(heading),nz=-Math.sin(heading);mesh.position.set(a.x+nx*lane,.03,a.y+nz*lane);mesh.rotation.y=heading;this.scene.add(mesh);const base=type==='bus'?7:type==='scooter'?8.5:8,target=type==='bus'?10:type==='scooter'?13:9+Math.random()*10;this.cars.push({id:++this.seq,mesh,road:r,seg,t:Math.random(),speed:base+Math.random()*7,targetSpeed:target,normalTarget:target,color,type,fuel:type==='scooter'?4+Math.random()*3:18+Math.random()*38,lane,heading,braking:false,crashed:0,hazard:false,reported:false});}
  }
  update(dt,focus=null,signals=null){
    for(const c of this.cars){const dFocus=focus?c.mesh.position.distanceTo(focus):0;c.mesh.visible=dFocus<720;if(dFocus>900)continue;
      let a=c.road.points[c.seg],b=c.road.points[c.seg+1];if(!b){c.seg=0;a=c.road.points[0];b=c.road.points[1];}const dx=b.x-a.x,dz=b.y-a.y,len=Math.hypot(dx,dz)||1,heading=Math.atan2(dx,dz);c.heading=heading;
      if(c.crashed>0){c.crashed-=dt;c.speed=THREE.MathUtils.lerp(c.speed,0,Math.min(1,dt*4.5));c.braking=true;c.hazard=true;if(c.crashed<=0){c.hazard=false;c.reported=false;c.targetSpeed=c.normalTarget;}this._lights(c);continue;}
      let desired=c.targetSpeed;if(dFocus<(c.type==='bus'?6.5:4.5))desired*=.08;else if(dFocus<11)desired*=.42;if(signals){const sig=signals.shouldStop(c.mesh.position,heading,15);if(sig.stop&&sig.distance<11.5)desired=Math.min(desired,Math.max(0,(sig.distance-3.2)*1.15));}
      let nearestAhead=999;const fwd=new THREE.Vector3(-Math.sin(heading),0,-Math.cos(heading));for(const o of this.cars){if(o===c||!o.mesh.visible)continue;const delta=o.mesh.position.clone().sub(c.mesh.position),ahead=delta.dot(fwd);if(ahead<=0||ahead>18)continue;const lateral=Math.abs(delta.x*fwd.z-delta.z*fwd.x),laneWidth=(c.type==='scooter'||o.type==='scooter')?1.25:2.0;if(lateral<laneWidth)nearestAhead=Math.min(nearestAhead,ahead);}if(nearestAhead<13)desired=Math.min(desired,Math.max(0,(nearestAhead-3.8)*1.15));
      const was=c.speed;c.speed=THREE.MathUtils.lerp(c.speed,desired,Math.min(1,dt*(desired<was?4.8:1.7)));c.braking=c.speed<was-.08;this._lights(c);c.t+=dt*c.speed/len;if(c.t>1){c.t=0;c.seg=(c.seg+1)%(c.road.points.length-1);}const aa=c.road.points[c.seg],bb=c.road.points[c.seg+1]||c.road.points[0],h=Math.atan2(bb.x-aa.x,bb.y-aa.y),nnx=Math.cos(h),nnz=-Math.sin(h);c.mesh.position.x=THREE.MathUtils.lerp(aa.x,bb.x,c.t)+nnx*c.lane;c.mesh.position.z=THREE.MathUtils.lerp(aa.y,bb.y,c.t)+nnz*c.lane;c.mesh.rotation.y=h;if(c.type==='scooter')c.mesh.rotation.z=THREE.MathUtils.lerp(c.mesh.rotation.z,Math.sin(performance.now()*.001+c.id)*.025,dt*3);
    }
  }
  _lights(c){const blink=Math.floor(performance.now()/330)%2===0;for(const lamp of c.mesh.userData.brake||[]){lamp.material.opacity=c.hazard?(blink?1:.15):(c.braking?1:.62);lamp.material.transparent=true;lamp.scale.setScalar((c.braking||c.hazard&&blink)?1.15:1);}}
  resolvePlayerCollision(car){if(!car)return 0;let severity=0;for(const c of this.cars){const radius=c.type==='bus'?3.6:c.type==='scooter'?1.4:2.55,d=car.group.position.distanceTo(c.mesh.position);if(d>radius)continue;const rel=Math.abs(car.velocity)+c.speed;const hit=Math.min(8,rel*.14);severity=Math.max(severity,hit);const away=car.group.position.clone().sub(c.mesh.position);away.y=0;if(away.lengthSq()<.01)away.set(1,0,0);away.normalize();car.group.position.addScaledVector(away,.22+hit*.035);car.velocity*=-.28;car.damage=Math.min(100,car.damage+1.2+hit*1.4);c.speed*=.25;c.targetSpeed=0;if(hit>2.4){c.crashed=Math.max(c.crashed,8+hit*1.7);c.hazard=true;if(!c.reported){c.reported=true;this.events.push({type:'crash',position:c.mesh.position.clone(),road:c.road,severity:hit,vehicleType:c.type});}}}return severity;}
  resolvePedestrianCollision(player){if(!player?.visible)return 0;let severity=0;for(const c of this.cars){if(c.crashed>0)continue;const radius=c.type==='bus'?1.8:c.type==='scooter'?.8:1.15,d=player.group.position.distanceTo(c.mesh.position);if(d>radius)continue;const hit=Math.min(7,Math.max(1,c.speed*.28));severity=Math.max(severity,hit);player.hit?.(c.mesh.position,hit);c.speed*=.35;c.crashed=Math.max(c.crashed,4+hit);c.hazard=true;if(!c.reported){c.reported=true;this.events.push({type:'pedestrian-hit',position:c.mesh.position.clone(),road:c.road,severity:hit,vehicleType:c.type});}}return severity;}
  drainEvents(){const out=this.events.splice(0,this.events.length);return out;}
  nearest(pos,max=4.8){let best=null,d=max;for(const c of this.cars){if(c.crashed>0)continue;const dd=c.mesh.position.distanceTo(pos);if(dd<d){best=c;d=dd;}}return best?{car:best,distance:d}:null;}
  take(c){const idx=this.cars.indexOf(c);if(idx<0)return null;this.cars.splice(idx,1);const out={position:c.mesh.position.clone(),heading:c.mesh.rotation.y,color:c.color,type:c.type,fuel:c.fuel,driverPos:c.mesh.position.clone(),road:c.road};this.scene.remove(c.mesh);setTimeout(()=>this.spawn(1),3500);return out;}
  dispose(){for(const c of this.cars)this.scene.remove(c.mesh);this.cars=[];}
}
